- name: Bağımlılıkları Kur (Libncurses Fix)
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev-i386 \
            libncurses5 libncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
            python3 python-is-python3 libssl-dev x11proto-core-dev libx11-dev \
            bison gperf
          
          # KRİTİK FİX: Eksik olan .so.5 kütüphanesini .so.6'ya bağlıyoruz
          sudo ln -s /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5
          sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
